#!/usr/bin/env python3
"""Create a sanitized peer metadata file for prometheus_wireguard_exporter.

The exporter needs readable config data to attach friendly_name/friendly_json
labels. Reading the real AmneziaWG server configs as an unprivileged exporter
user is inconvenient and unnecessarily exposes PrivateKey/PresharedKey values.
This helper reads the real configs as root and writes only safe peer metadata.
"""
from __future__ import annotations

import argparse
import os
import pwd
import grp
import re
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

FRIENDLY_RE = re.compile(r"^\s*#\s*(friendly_name|friendly_json)\s*=\s*(.*?)\s*$")
SECTION_RE = re.compile(r"^\s*\[([^]]+)\]\s*$")
KV_RE = re.compile(r"^\s*([A-Za-z0-9_]+)\s*=\s*(.*?)\s*$")


@dataclass
class PeerBlock:
    source: str
    source_interface: str
    public_key: str = ""
    allowed_ips: str = ""
    friendly: List[str] = field(default_factory=list)
    extra_comments: List[str] = field(default_factory=list)


def normalize_friendly_comment(line: str) -> Optional[str]:
    match = FRIENDLY_RE.match(line)
    if not match:
        return None
    key, value = match.groups()
    value = value.strip()
    if not value:
        return None
    return f"# {key} = {value}"


def parse_config(path: Path) -> List[PeerBlock]:
    interface = path.name[:-5] if path.name.endswith(".conf") else path.stem
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError as exc:
        raise RuntimeError(f"cannot read {path}: {exc}") from exc

    peers: List[PeerBlock] = []
    pending_friendly: List[str] = []
    current: Optional[PeerBlock] = None
    in_peer = False

    def flush() -> None:
        nonlocal current
        if current and current.public_key:
            # Keep order while removing duplicate friendly comments inside one peer block.
            seen = set()
            unique_friendly = []
            for item in current.friendly:
                if item not in seen:
                    seen.add(item)
                    unique_friendly.append(item)
            current.friendly = unique_friendly
            peers.append(current)
        current = None

    for raw_line in lines:
        section = SECTION_RE.match(raw_line)
        if section:
            name = section.group(1).strip().lower()
            if in_peer:
                flush()
            in_peer = name == "peer"
            if in_peer:
                current = PeerBlock(source=str(path), source_interface=interface, friendly=list(pending_friendly))
            pending_friendly = []
            continue

        friendly = normalize_friendly_comment(raw_line)
        if friendly:
            if in_peer and current is not None:
                current.friendly.append(friendly)
            else:
                # Support the common but fragile style where the comment is placed
                # immediately before [Peer]. The sanitized file moves it into the peer.
                pending_friendly.append(friendly)
            continue

        if not in_peer or current is None:
            # Non-friendly comments should not float across unrelated sections.
            if raw_line.strip() and not raw_line.lstrip().startswith("#"):
                pending_friendly = []
            continue

        kv = KV_RE.match(raw_line)
        if not kv:
            continue
        key, value = kv.group(1), kv.group(2).strip()
        key_lower = key.lower()
        if key_lower == "publickey":
            current.public_key = value
        elif key_lower == "allowedips":
            current.allowed_ips = value
        # Intentionally ignore PrivateKey, PresharedKey, Endpoint, and other secrets.

    if in_peer:
        flush()
    return peers


def render_sanitized(peers: Iterable[PeerBlock]) -> str:
    out: List[str] = []
    out.append("# Generated by awg-exporter-sync-peers. Do not edit manually.")
    out.append("# This file intentionally contains only public peer metadata.")
    out.append("")
    seen_public_keys: Dict[str, PeerBlock] = {}
    for peer in peers:
        if peer.public_key in seen_public_keys:
            # prometheus_wireguard_exporter merges config files in memory; duplicate
            # public keys can make labels ambiguous. Keep the first definition.
            continue
        seen_public_keys[peer.public_key] = peer
        out.append(f"# source_file = {peer.source}")
        out.append(f"# source_interface = {peer.source_interface}")
        out.append("[Peer]")
        for item in peer.friendly:
            out.append(item)
        out.append(f"PublicKey = {peer.public_key}")
        if peer.allowed_ips:
            out.append(f"AllowedIPs = {peer.allowed_ips}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def parse_owner(owner: str) -> Tuple[int, int]:
    if ":" in owner:
        user, group = owner.split(":", 1)
    else:
        user, group = owner, owner
    uid = pwd.getpwnam(user).pw_uid if not user.isdigit() else int(user)
    gid = grp.getgrnam(group).gr_gid if not group.isdigit() else int(group)
    return uid, gid


def atomic_write(path: Path, data: str, owner: Optional[str], mode: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(data)
            fh.flush()
            os.fsync(fh.fileno())
        if owner:
            uid, gid = parse_owner(owner)
            os.chown(tmp_name, uid, gid)
        os.chmod(tmp_name, int(mode, 8))
        os.replace(tmp_name, path)
    finally:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Build sanitized peer metadata for prometheus_wireguard_exporter")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--owner", default="root:wgexporter")
    parser.add_argument("--mode", default="0640")
    parser.add_argument("--configs", nargs="+", required=True, type=Path)
    args = parser.parse_args(argv)

    all_peers: List[PeerBlock] = []
    errors: List[str] = []
    for config in args.configs:
        try:
            all_peers.extend(parse_config(config))
        except Exception as exc:
            errors.append(str(exc))

    if errors:
        for err in errors:
            print(f"ERROR: {err}", file=sys.stderr)
        return 1
    if not all_peers:
        print("ERROR: no peers found in the provided configs", file=sys.stderr)
        return 1

    data = render_sanitized(all_peers)
    atomic_write(args.output, data, args.owner, args.mode)
    print(f"Wrote {args.output} with {len(all_peers)} peer block(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
