#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./00_common.sh
source "${SCRIPT_DIR}/00_common.sh"

SSH_PORT_DEFAULT="${SSH_PORT_DEFAULT:-22}"
EXTERNAL_IF_DEFAULT="${EXTERNAL_IF_DEFAULT:-}"
TARGET_VPN_IF="${TARGET_VPN_IF:-}"

usage() {
    cat <<'EOF_USAGE'
03_setup_nftables.sh

Создаёт единый IPv4 firewall/NAT ruleset для всех найденных AmneziaWG интерфейсов:
  /etc/amnezia/amneziawg/*.conf

Важно:
  - скрипт собирает UDP ListenPort по каждому .conf и добавляет все порты;
  - NAT masquerade добавляется для всех AWG интерфейсов;
  - старые awg0/awg1 не удаляются из правил;
  - итоговый файл по умолчанию пишется в /etc/nftables.conf;
  - ruleset содержит flush ruleset, поэтому он заменяет текущие nftables-правила сервера.

Переменные:
  TARGET_VPN_IF=awg1    - включить/перезапустить service только для указанного интерфейса;
  EXTERNAL_IF_DEFAULT=ens3
  SSH_PORT_DEFAULT=22
EOF_USAGE
}

if [[ "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

collect_interfaces() {
    local iface conf port
    while IFS= read -r iface; do
        conf="$(server_conf_for_iface "$iface")"
        [[ -f "$conf" ]] || continue
        port="$(get_conf_value "$conf" "ListenPort" || true)"
        [[ -n "$port" ]] || continue
        if ! validate_port "$port" >/dev/null 2>&1; then
            warn "Пропускаю ${conf}: некорректный ListenPort=${port}"
            continue
        fi
        printf '%s:%s\n' "$iface" "$port"
    done < <(list_awg_interfaces_from_confs)
}

generate_ruleset() {
    local ext_if="$1"
    local ssh_port="$2"
    local pairs="$3"
    local ports ifaces pair iface port first

    ports=""
    ifaces=""
    first=1
    while IFS= read -r pair; do
        [[ -n "$pair" ]] || continue
        iface="${pair%%:*}"
        port="${pair##*:}"
        if [[ "$first" -eq 1 ]]; then
            ports="$port"
            ifaces="\"$iface\""
            first=0
        else
            ports="$ports, $port"
            ifaces="$ifaces, \"$iface\""
        fi
    done <<< "$pairs"

    [[ -n "$ports" ]] || die "Не найден ни один AWG конфиг с ListenPort в $STATE_DIR/*.conf"

    cat <<EOF_RULES
flush ruleset

# Generated by AmneziaWG bash bundle.
# IPv4 forwarding/NAT for all configured AWG interfaces.

table ip filter {
    chain input {
        type filter hook input priority 0; policy drop;
        iif "lo" accept
        ct state established,related accept
        tcp dport ${ssh_port} accept
        iifname "${ext_if}" udp dport { ${ports} } accept
        ip protocol icmp icmp type { echo-request, echo-reply, destination-unreachable, time-exceeded, parameter-problem } accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
        iifname { ${ifaces} } accept
        oifname { ${ifaces} } ct state established,related accept
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}

table ip nat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        iifname { ${ifaces} } oifname "${ext_if}" masquerade
    }
}
EOF_RULES
}

main() {
    local ext_if ssh_port rules_tmp backup pairs iface service_name existing_nft_hint

    require_root
    require_cmd nft
    require_cmd systemctl

    source_env_if_exists "$MANAGER_ENV_FILE"
    source_env_if_exists "$FIREWALL_ENV_FILE"
    ext_if="$(prompt_default "Внешний интерфейс" "${EXTERNAL_IF_DEFAULT:-${EXTERNAL_IF:-$(detect_default_interface)}}")"
    [[ -n "$ext_if" ]] || die "Внешний интерфейс не может быть пустым"
    ssh_port="$(prompt_until_valid "SSH порт" "${SSH_PORT_DEFAULT:-${SSH_PORT:-22}}" validate_port)"

    pairs="$(collect_interfaces)"
    [[ -n "$pairs" ]] || die "Не найден ни один серверный конфиг AWG в $STATE_DIR/*.conf"

    rules_tmp="$(mktemp)"
    generate_ruleset "$ext_if" "$ssh_port" "$pairs" > "$rules_tmp"

    printf '\nНайдены AWG интерфейсы и порты:\n%s\n' "$pairs"
    if [[ -f "$NFTABLES_CONF" ]] && ! grep -q 'Generated by AmneziaWG bash bundle' "$NFTABLES_CONF" 2>/dev/null; then
        existing_nft_hint="yes"
        warn "${NFTABLES_CONF} уже существует и, похоже, создан не этим bundle. Новый ruleset заменит текущие правила."
    fi
    printf '\nПредварительный просмотр правил nftables:\n\n'
    cat "$rules_tmp"
    printf '\nПроверяю синтаксис через nft -c -f ...\n'
    nft -c -f "$rules_tmp"
    ok "Синтаксис nftables корректный"

    if confirm "Сохранить правила в ${NFTABLES_CONF}, применить их и включить автозагрузку nftables?" Y; then
        backup="$(backup_file "$NFTABLES_CONF" || true)"
        [[ -n "$backup" ]] && warn "Старый ${NFTABLES_CONF} сохранён в: $backup"
        ensure_dir "$(dirname "$NFTABLES_CONF")"
        cp "$rules_tmp" "$NFTABLES_CONF"
        nft -f "$NFTABLES_CONF"
        systemctl enable --now nftables
        write_firewall_env "$FIREWALL_ENV_FILE" "$ext_if" "$ssh_port"
        ok "Правила применены и сохранены в $NFTABLES_CONF"
        ok "Параметры firewall сохранены в $FIREWALL_ENV_FILE"
    else
        warn "Правила не были применены"
        rm -f "$rules_tmp"
        exit 0
    fi

    while IFS=: read -r iface _port; do
        [[ -n "$iface" ]] || continue
        if [[ -n "$TARGET_VPN_IF" && "$iface" != "$TARGET_VPN_IF" ]]; then
            continue
        fi
        service_name="awg-quick@${iface}.service"
        systemctl enable "$service_name"
        systemctl restart "$service_name" || systemctl start "$service_name"
        ok "${service_name} включён в автозагрузку и перезапущен"
    done <<< "$pairs"

    rm -f "$rules_tmp"
    printf '\nСледующий шаг: scripts/04_add_client.sh <имя_клиента> [interface] или scripts/00_manage.sh\n'
}

main "$@"
