#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./00_common.sh
source "${SCRIPT_DIR}/00_common.sh"

SSH_PORT_DEFAULT="${SSH_PORT_DEFAULT:-22}"
EXTERNAL_IF_DEFAULT="${EXTERNAL_IF_DEFAULT:-}"
TARGET_VPN_IF="${TARGET_VPN_IF:-}"
NFT_TABLE_NAME="${NFT_TABLE_NAME:-amneziawg_bundle}"

usage() {
    cat <<'EOF_USAGE'
03_setup_nftables.sh

Создаёт/дополняет IPv4 firewall/NAT правила для всех найденных AmneziaWG интерфейсов:
  /etc/amnezia/amneziawg/*.conf

Важно по сохранности старых данных:
  - существующий /etc/nftables.conf не перезаписывается;
  - если файла ещё нет, создаётся новый bundle-owned конфиг;
  - если файл уже есть, в конец дописывается новый блок/команды AmneziaWG;
  - глобальный flush ruleset не используется, чтобы не сбрасывать старые runtime-правила;
  - старые правила, старые строки и старые AWG интерфейсы не удаляются.

Переменные:
  TARGET_VPN_IF=awg1    - включить/перезапустить service только для указанного интерфейса;
  EXTERNAL_IF_DEFAULT=ens3
  SSH_PORT_DEFAULT=22
  NFT_TABLE_NAME=amneziawg_bundle
EOF_USAGE
}

if [[ "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

collect_interfaces() {
    local iface conf port
    while IFS= read -r iface; do
        conf="$(server_conf_for_iface "$iface")"
        [[ -f "$conf" ]] || continue
        port="$(get_conf_value "$conf" "ListenPort" || true)"
        [[ -n "$port" ]] || continue
        if ! validate_port "$port" >/dev/null 2>&1; then
            warn "Пропускаю ${conf}: некорректный ListenPort=${port}"
            continue
        fi
        printf '%s:%s\n' "$iface" "$port"
    done < <(list_awg_interfaces_from_confs)
}

pairs_to_sets() {
    local pairs="$1"
    local ports="" ifaces="" pair iface port first
    first=1
    while IFS= read -r pair; do
        [[ -n "$pair" ]] || continue
        iface="${pair%%:*}"
        port="${pair##*:}"
        if [[ "$first" -eq 1 ]]; then
            ports="$port"
            ifaces="\"$iface\""
            first=0
        else
            ports="$ports, $port"
            ifaces="$ifaces, \"$iface\""
        fi
    done <<< "$pairs"
    [[ -n "$ports" ]] || die "Не найден ни один AWG конфиг с ListenPort в $STATE_DIR/*.conf"
    printf '%s\n%s\n' "$ports" "$ifaces"
}

generate_bundle_table() {
    local ext_if="$1"
    local ssh_port="$2"
    local pairs="$3"
    local include_flush="${4:-no}"
    local ports ifaces
    local -a _sets
    mapfile -t _sets < <(pairs_to_sets "$pairs")
    ports="${_sets[0]}"
    ifaces="${_sets[1]}"

    # include_flush сохранён в сигнатуре для совместимости, но глобальный flush ruleset
    # намеренно не выводится: старые runtime-правила nftables нельзя сбрасывать.

    cat <<EOF_RULES
# Generated by AmneziaWG bash bundle.
# Append-safe IPv4 forwarding/NAT for configured AWG interfaces.

table ip ${NFT_TABLE_NAME} {
    set vpn_ports {
        type inet_service
        elements = { ${ports} }
    }

    set vpn_ifaces {
        type ifname
        elements = { ${ifaces} }
    }

    chain input {
        type filter hook input priority 0; policy accept;
        iif "lo" accept
        ct state established,related accept
        tcp dport ${ssh_port} accept
        iifname "${ext_if}" udp dport @vpn_ports accept
        ip protocol icmp icmp type { echo-request, echo-reply, destination-unreachable, time-exceeded, parameter-problem } accept
    }

    chain forward {
        type filter hook forward priority 0; policy accept;
        iifname @vpn_ifaces accept
        oifname @vpn_ifaces ct state established,related accept
    }

    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        iifname @vpn_ifaces oifname "${ext_if}" masquerade
    }
}
EOF_RULES
}

file_mentions_port() {
    local file="$1"
    local port="$2"
    [[ -f "$file" ]] && grep -Eq "(^|[^0-9])${port}([^0-9]|$)" "$file"
}

file_mentions_quoted() {
    local file="$1"
    local value="$2"
    [[ -f "$file" ]] && grep -Fq "\"${value}\"" "$file"
}

generate_append_commands() {
    local file="$1"
    local ext_if="$2"
    local ssh_port="$3"
    local pairs="$4"
    local pair iface port wrote="no"

    printf '# Generated by AmneziaWG bash bundle. Append-only update.\n'
    while IFS= read -r pair; do
        [[ -n "$pair" ]] || continue
        iface="${pair%%:*}"
        port="${pair##*:}"
        if ! file_mentions_port "$file" "$port"; then
            printf 'add element ip %s vpn_ports { %s }\n' "$NFT_TABLE_NAME" "$port"
            wrote="yes"
        fi
        if ! file_mentions_quoted "$file" "$iface"; then
            printf 'add element ip %s vpn_ifaces { "%s" }\n' "$NFT_TABLE_NAME" "$iface"
            wrote="yes"
        fi
    done <<< "$pairs"

    if ! file_mentions_port "$file" "$ssh_port"; then
        printf 'add rule ip %s input tcp dport %s accept\n' "$NFT_TABLE_NAME" "$ssh_port"
        wrote="yes"
    fi
    if ! file_mentions_quoted "$file" "$ext_if"; then
        printf 'add rule ip %s input iifname "%s" udp dport @vpn_ports accept\n' "$NFT_TABLE_NAME" "$ext_if"
        printf 'add rule ip %s postrouting iifname @vpn_ifaces oifname "%s" masquerade\n' "$NFT_TABLE_NAME" "$ext_if"
        wrote="yes"
    fi

    if [[ "$wrote" == "no" ]]; then
        printf '# No new AmneziaWG nftables elements were needed.\n'
    fi
}

main() {
    local ext_if ssh_port rules_tmp pairs iface service_name mode

    require_root
    require_cmd nft
    require_cmd systemctl

    source_env_if_exists "$MANAGER_ENV_FILE"
    source_env_if_exists "$FIREWALL_ENV_FILE"
    ext_if="$(prompt_default "Внешний интерфейс" "${EXTERNAL_IF_DEFAULT:-${EXTERNAL_IF:-$(detect_default_interface)}}")"
    [[ -n "$ext_if" ]] || die "Внешний интерфейс не может быть пустым"
    ssh_port="$(prompt_until_valid "SSH порт" "${SSH_PORT_DEFAULT:-${SSH_PORT:-22}}" validate_port)"

    pairs="$(collect_interfaces)"
    [[ -n "$pairs" ]] || die "Не найден ни один серверный конфиг AWG в $STATE_DIR/*.conf"

    rules_tmp="$(mktemp)"
    if [[ ! -e "$NFTABLES_CONF" ]]; then
        mode="create"
        generate_bundle_table "$ext_if" "$ssh_port" "$pairs" yes > "$rules_tmp"
    elif grep -q "table ip ${NFT_TABLE_NAME}" "$NFTABLES_CONF" 2>/dev/null; then
        mode="append-commands"
        generate_append_commands "$NFTABLES_CONF" "$ext_if" "$ssh_port" "$pairs" > "$rules_tmp"
    else
        mode="append-table"
        warn "${NFTABLES_CONF} уже существует. Не перезаписываю его; добавлю отдельный table ip ${NFT_TABLE_NAME} в конец файла."
        generate_bundle_table "$ext_if" "$ssh_port" "$pairs" no > "$rules_tmp"
    fi

    printf '\nНайдены AWG интерфейсы и порты:\n%s\n' "$pairs"
    printf '\nРежим записи nftables: %s\n' "$mode"
    printf '\nПредварительный просмотр добавляемых правил/команд nftables:\n\n'
    cat "$rules_tmp"
    printf '\nПроверяю синтаксис через nft -c -f ...\n'
    nft -c -f "$rules_tmp"
    ok "Синтаксис nftables корректный"

    if confirm "Сохранить/дописать правила в ${NFTABLES_CONF}, применить их и включить автозагрузку nftables?" Y; then
        if [[ "$mode" == "create" ]]; then
            cat "$rules_tmp" | write_new_file_from_stdin "$NFTABLES_CONF" 644
            nft -f "$NFTABLES_CONF"
        else
            cat "$rules_tmp" | append_or_create_file_from_stdin "$NFTABLES_CONF" 644
            nft -f "$rules_tmp"
        fi
        systemctl enable --now nftables
        write_firewall_env "$FIREWALL_ENV_FILE" "$ext_if" "$ssh_port"
        ok "Правила сохранены без перезаписи старого файла: $NFTABLES_CONF"
        ok "Параметры firewall сохранены append-only в $FIREWALL_ENV_FILE"
    else
        warn "Правила не были применены"
        rm -f "$rules_tmp"
        exit 0
    fi

    while IFS=: read -r iface _port; do
        [[ -n "$iface" ]] || continue
        if [[ -n "$TARGET_VPN_IF" && "$iface" != "$TARGET_VPN_IF" ]]; then
            continue
        fi
        service_name="awg-quick@${iface}.service"
        systemctl enable "$service_name"
        systemctl restart "$service_name" || systemctl start "$service_name"
        ok "${service_name} включён в автозагрузку и перезапущен"
    done <<< "$pairs"

    rm -f "$rules_tmp"
    printf '\nСледующий шаг: scripts/04_add_client.sh <имя_клиента> [interface] или scripts/00_manage.sh\n'
}

main "$@"
