#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./00_common.sh
source "${SCRIPT_DIR}/00_common.sh"

SSH_PORT_DEFAULT="${SSH_PORT_DEFAULT:-22}"
EXTERNAL_IF_DEFAULT="${EXTERNAL_IF_DEFAULT:-}"
TARGET_VPN_IF="${TARGET_VPN_IF:-}"
NFT_TABLE_NAME="${NFT_TABLE_NAME:-amneziawg_bundle}"
NFT_APPLY_NOW="${NFT_APPLY_NOW:-ask}"       # yes|no|ask
NFT_SAVE_CHANGES="${NFT_SAVE_CHANGES:-ask}" # yes|no|ask
ALLOW_NO_INTERFACES="${ALLOW_NO_INTERFACES:-no}"
EXTRA_AWG_PORTS_TO_REMOVE="${EXTRA_AWG_PORTS_TO_REMOVE:-}"
EXTRA_AWG_IFACES_TO_REMOVE="${EXTRA_AWG_IFACES_TO_REMOVE:-}"

usage() {
    cat <<'EOF_USAGE'
03_setup_nftables.sh

Пересобирает /etc/nftables.conf для всех найденных AmneziaWG интерфейсов:
  /etc/amnezia/amneziawg/*.conf

Логика этой версии:
  - файл nftables.conf перезаписывается итоговым candidate, а не дописывается;
  - перед перезаписью создаётся timestamp backup с MANIFEST.tsv;
  - итоговый файл начинается с `flush ruleset`, поэтому `nft -f /etc/nftables.conf` заменяет runtime ruleset, а не наслаивает правила;
  - в table inet filter/input базовые правила loopback/established/SSH/ICMP нормализуются и не дублируются;
  - AWG UDP-порты объединяются в одно правило вида `iifname "ens3" udp dport { ... } accept`;
  - NAT masquerade объединяется в одно правило вида `iifname { "awg0", "awg1" } oifname "ens3" masquerade`;
  - существующие пользовательские правила, например redirect UDP 53/443 или доступ к Grafana с awg0, сохраняются;
  - старые table ip amneziawg_bundle удаляются из candidate.

Переменные:
  EXTERNAL_IF_DEFAULT=ens3
  SSH_PORT_DEFAULT=22
  NFT_APPLY_NOW=yes|no|ask
  NFT_SAVE_CHANGES=yes|no|ask
  ALLOW_NO_INTERFACES=yes       - разрешить очистку AWG-правил, если интерфейсов больше нет (используется удалением интерфейса)
  EXTRA_AWG_PORTS_TO_REMOVE=520 - дополнительные старые порты для удаления из ruleset
  EXTRA_AWG_IFACES_TO_REMOVE=awg1 - дополнительные старые ifaces для удаления из NAT
EOF_USAGE
}

if [[ "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

collect_interfaces() {
    local iface conf port
    while IFS= read -r iface; do
        conf="$(server_conf_for_iface "$iface")"
        [[ -f "$conf" ]] || continue
        port="$(get_conf_value "$conf" "ListenPort" || true)"
        [[ -n "$port" ]] || continue
        if ! validate_port "$port" >/dev/null 2>&1; then
            warn "Пропускаю ${conf}: некорректный ListenPort=${port}"
            continue
        fi
        printf '%s:%s\n' "$iface" "$port"
    done < <(list_awg_interfaces_from_confs)
}

csv_unique_append() {
    local base="${1:-}"
    local extra="${2:-}"
    local out="" item seen=""
    for item in ${base//,/ } ${extra//,/ }; do
        item="${item//[[:space:]]/}"
        [[ -n "$item" ]] || continue
        if grep -qxF "$item" <<< "$seen" 2>/dev/null; then
            continue
        fi
        seen="${seen}"$'\n'"${item}"
        if [[ -z "$out" ]]; then out="$item"; else out="${out},${item}"; fi
    done
    printf '%s\n' "$out"
}

pairs_to_csv() {
    local pairs="$1"
    local field="$2"
    local pair value seen="" out=""
    while IFS= read -r pair; do
        [[ -n "$pair" ]] || continue
        if [[ "$field" == "ports" ]]; then
            value="${pair##*:}"
        else
            value="${pair%%:*}"
        fi
        if grep -qxF "$value" <<< "$seen" 2>/dev/null; then
            continue
        fi
        seen="${seen}"$'\n'"${value}"
        if [[ -z "$out" ]]; then
            out="$value"
        else
            out="${out},${value}"
        fi
    done <<< "$pairs"
    printf '%s\n' "$out"
}

csv_to_nft_ports() {
    local csv="$1"
    local out="" item
    [[ -n "$csv" ]] || return 1
    IFS=',' read -r -a _items <<< "$csv"
    for item in "${_items[@]}"; do
        item="${item//[[:space:]]/}"
        [[ -n "$item" ]] || continue
        if [[ -z "$out" ]]; then out="$item"; else out="$out, $item"; fi
    done
    [[ -n "$out" ]] || return 1
    printf '{ %s }' "$out"
}

csv_to_nft_ifaces() {
    local csv="$1"
    local out="" item
    [[ -n "$csv" ]] || return 1
    IFS=',' read -r -a _items <<< "$csv"
    for item in "${_items[@]}"; do
        item="${item//[[:space:]]/}"
        [[ -n "$item" ]] || continue
        if [[ -z "$out" ]]; then out="\"$item\""; else out="$out, \"$item\""; fi
    done
    [[ -n "$out" ]] || return 1
    printf '{ %s }' "$out"
}

generate_native_template() {
    local ext_if="$1"
    local ssh_port="$2"
    local ports_csv="$3"
    local ifaces_csv="$4"
    local ports_set ifaces_set
    ports_set="$(csv_to_nft_ports "$ports_csv" 2>/dev/null || true)"
    ifaces_set="$(csv_to_nft_ifaces "$ifaces_csv" 2>/dev/null || true)"
    cat <<EOF_RULES
flush ruleset

# Generated by AmneziaWG bash bundle.
# Full ruleset is regenerated from current AWG configs; old AWG duplicates are not appended.

table inet filter {
        chain input {
                type filter hook input priority filter; policy drop;
                iif "lo" accept
                ct state established,related accept
                tcp dport ${ssh_port} accept
                ip protocol icmp icmp type { echo-reply, destination-unreachable, echo-request, time-exceeded, parameter-problem } accept
EOF_RULES
    if [[ -n "$ports_set" ]]; then
        printf '                iifname "%s" udp dport %s accept\n' "$ext_if" "$ports_set"
    fi
    cat <<'EOF_RULES'
        }

        chain forward {
                type filter hook forward priority filter; policy accept;
        }

        chain output {
                type filter hook output priority filter; policy accept;
        }
}

table inet nat {
        chain postrouting {
                type nat hook postrouting priority srcnat; policy accept;
EOF_RULES
    if [[ -n "$ifaces_set" ]]; then
        printf '                iifname %s oifname "%s" masquerade\n' "$ifaces_set" "$ext_if"
    fi
    cat <<'EOF_RULES'
        }
}
EOF_RULES
}

render_native_update() {
    local src="$1"
    local dst="$2"
    local ext_if="$3"
    local ssh_port="$4"
    local ports_csv="$5"
    local ifaces_csv="$6"
    local remove_ports_csv="$7"
    local remove_ifaces_csv="$8"

    command -v python3 >/dev/null 2>&1 || return 41
    python3 -S - "$src" "$dst" "$ext_if" "$ssh_port" "$ports_csv" "$ifaces_csv" "$remove_ports_csv" "$remove_ifaces_csv" "$NFT_TABLE_NAME" <<'PY'
import re
import sys
from pathlib import Path

src, dst, ext_if, ssh_port, ports_csv, ifaces_csv, remove_ports_csv, remove_ifaces_csv, table_name = sys.argv[1:]
text = Path(src).read_text()
ports = [p.strip() for p in ports_csv.split(',') if p.strip()]
ifaces = [i.strip() for i in ifaces_csv.split(',') if i.strip()]
remove_ports = set(p.strip() for p in remove_ports_csv.split(',') if p.strip()) | set(ports)
remove_ifaces = set(i.strip() for i in remove_ifaces_csv.split(',') if i.strip()) | set(ifaces)
ports_set = '{ ' + ', '.join(ports) + ' }' if ports else ''
ifaces_set = '{ ' + ', '.join(f'"{i}"' for i in ifaces) + ' }' if ifaces else ''


def ensure_flush_ruleset(s: str) -> str:
    s = re.sub(r'(?m)^\s*flush\s+ruleset\s*\n+', '', s)
    return 'flush ruleset\n\n' + s.lstrip('\n')


def find_block(s, pattern, start=0, end=None):
    limit = len(s) if end is None else end
    lines = []
    pos = start
    for line in s[start:limit].splitlines(True):
        lines.append((pos, line))
        pos += len(line)
    start_idx = None
    for idx, (_pos, line) in enumerate(lines):
        if re.search(pattern, line):
            start_idx = idx
            break
    if start_idx is None:
        return None
    depth = 0
    block_start = lines[start_idx][0]
    for idx in range(start_idx, len(lines)):
        line_start, line = lines[idx]
        stripped = line.strip()
        if idx == start_idx:
            if '{' not in line:
                return None
            depth = 1
        else:
            if re.match(r'^(table|chain|set)\b.*\{\s*(#.*)?$', stripped):
                depth += 1
            if re.match(r'^}\s*(#.*)?$', stripped):
                depth -= 1
                if depth == 0:
                    return block_start, line_start + len(line)
    return None


def remove_table_ip_bundle(s):
    changed = False
    while True:
        block = find_block(s, rf'^[ \t]*table[ \t]+ip[ \t]+{re.escape(table_name)}[ \t]*\{{')
        if not block:
            return s, changed
        a, b = block
        while b < len(s) and s[b] in ' \t\r\n':
            if s[b] == '\n':
                b += 1
                break
            b += 1
        s = s[:a].rstrip() + '\n\n' + s[b:].lstrip('\n')
        changed = True


def line_ports(line):
    m = re.search(r'\budp\s+dport\s+(\{[^}]*\}|[0-9]+)', line)
    if not m:
        return set()
    return set(re.findall(r'(?<!\d)(\d{1,5})(?!\d)', m.group(1)))


def line_is_awg_port_rule(line):
    nums = line_ports(line)
    if not nums or not remove_ports:
        return False
    return (f'iifname "{ext_if}"' in line and 'udp' in line and 'dport' in line
            and 'accept' in line and nums.issubset(remove_ports))


def iifaces_in_line(line):
    m = re.search(r'\biifname\s+\{([^}]*)\}', line)
    if m:
        return re.findall(r'"([^"]+)"', m.group(1))
    m = re.search(r'\biifname\s+"([^"]+)"', line)
    if m:
        return [m.group(1)]
    return []


def line_is_awg_nat_rule(line):
    names = set(iifaces_in_line(line))
    if not names or not remove_ifaces:
        return False
    return 'masquerade' in line and f'oifname "{ext_if}"' in line and names.issubset(remove_ifaces)


def replace_block(s, block, new_block):
    a, b = block
    return s[:a] + new_block + s[b:]


def is_base_input_rule(stripped):
    if stripped in {'iif "lo" accept', "iif 'lo' accept"}:
        return True
    if stripped == 'ct state established,related accept':
        return True
    if re.fullmatch(rf'tcp\s+dport\s+(?:\{{[^}}]*\b{re.escape(ssh_port)}\b[^}}]*\}}|{re.escape(ssh_port)})\s+accept', stripped):
        return True
    if 'ip protocol icmp' in stripped and 'accept' in stripped:
        return True
    return False


def update_input_chain(chain):
    if 'policy drop' not in chain:
        raise RuntimeError('input chain policy is not drop; refusing to change policy automatically')
    lines = chain.splitlines()
    new_lines = []
    seen_rules = set()
    hook_idx = None
    for line in lines:
        stripped = line.strip()
        if 'type filter hook input' in line:
            hook_idx = len(new_lines)
            new_lines.append(line)
            continue
        if is_base_input_rule(stripped):
            continue
        if line_is_awg_port_rule(line):
            continue
        # Deduplicate exact remaining rules inside the chain, but keep braces/comments readable.
        if stripped and not stripped.startswith('#') and stripped not in {'chain input {', '}'}:
            key = re.sub(r'\s+', ' ', stripped)
            if key in seen_rules:
                continue
            seen_rules.add(key)
        new_lines.append(line)
    if hook_idx is None:
        raise RuntimeError('cannot find hook line in input chain')
    indent = re.match(r'^(\s*)', new_lines[hook_idx]).group(1)
    canonical = [
        f'{indent}iif "lo" accept',
        f'{indent}ct state established,related accept',
        f'{indent}tcp dport {ssh_port} accept',
        f'{indent}ip protocol icmp icmp type {{ echo-reply, destination-unreachable, echo-request, time-exceeded, parameter-problem }} accept',
    ]
    if ports:
        canonical.append(f'{indent}iifname "{ext_if}" udp dport {ports_set} accept')
    for offset, line in enumerate(canonical, 1):
        new_lines.insert(hook_idx + offset, line)
    return '\n'.join(new_lines) + ('\n' if chain.endswith('\n') else '')


def update_postrouting_chain(chain):
    lines = chain.splitlines()
    new_lines = []
    seen_rules = set()
    hook_idx = None
    for line in lines:
        stripped = line.strip()
        if 'type nat hook postrouting' in line:
            hook_idx = len(new_lines)
            new_lines.append(line)
            continue
        if line_is_awg_nat_rule(line):
            continue
        if stripped and not stripped.startswith('#') and stripped not in {'chain postrouting {', '}'}:
            key = re.sub(r'\s+', ' ', stripped)
            if key in seen_rules:
                continue
            seen_rules.add(key)
        new_lines.append(line)
    if hook_idx is None:
        raise RuntimeError('cannot find hook line in postrouting chain')
    if ifaces:
        indent = re.match(r'^(\s*)', new_lines[hook_idx]).group(1)
        new_lines.insert(hook_idx + 1, f'{indent}iifname {ifaces_set} oifname "{ext_if}" masquerade')
    return '\n'.join(new_lines) + ('\n' if chain.endswith('\n') else '')


try:
    text, _removed_bundle = remove_table_ip_bundle(text)
    filter_table = find_block(text, r'^[ \t]*table[ \t]+inet[ \t]+filter[ \t]*\{')
    nat_table = find_block(text, r'^[ \t]*table[ \t]+inet[ \t]+nat[ \t]*\{')
    if not filter_table or not nat_table:
        raise RuntimeError('expected table inet filter and table inet nat')
    input_chain = find_block(text, r'^[ \t]*chain[ \t]+input[ \t]*\{', filter_table[0], filter_table[1])
    post_chain = find_block(text, r'^[ \t]*chain[ \t]+postrouting[ \t]*\{', nat_table[0], nat_table[1])
    if not input_chain:
        raise RuntimeError('expected chain input inside table inet filter')
    if not post_chain:
        raise RuntimeError('expected chain postrouting inside table inet nat')

    old_input = text[input_chain[0]:input_chain[1]]
    new_input = update_input_chain(old_input)
    text = replace_block(text, input_chain, new_input)

    nat_table = find_block(text, r'^[ \t]*table[ \t]+inet[ \t]+nat[ \t]*\{')
    post_chain = find_block(text, r'^[ \t]*chain[ \t]+postrouting[ \t]*\{', nat_table[0], nat_table[1])
    old_post = text[post_chain[0]:post_chain[1]]
    new_post = update_postrouting_chain(old_post)
    text = replace_block(text, post_chain, new_post)

    text = ensure_flush_ruleset(text)
    Path(dst).write_text(text.rstrip() + '\n')
except Exception as exc:
    print(str(exc), file=sys.stderr)
    sys.exit(42)
PY
}

print_manual_nft_instructions() {
    local reason="$1"
    local ext_if="$2"
    local ssh_port="$3"
    local ports_csv="$4"
    local ifaces_csv="$5"
    local ports_set ifaces_set
    ports_set="$(csv_to_nft_ports "$ports_csv" 2>/dev/null || true)"
    ifaces_set="$(csv_to_nft_ifaces "$ifaces_csv" 2>/dev/null || true)"
    warn "Автоматически менять nftables небезопасно: ${reason}"
    cat <<EOF_MANUAL

Ручной безопасный вариант для ${NFTABLES_CONF}:

1) Сделайте backup:
   sudo mkdir -p /etc/amnezia/amneziawg/backups/$(date +%Y%m%d-%H%M%S)-manual-nftables
   sudo cp -a ${NFTABLES_CONF} /etc/amnezia/amneziawg/backups/$(date +%Y%m%d-%H%M%S)-manual-nftables/

2) Уберите дубли старых AWG-правил из table inet filter / chain input.
3) Убедитесь, что базовые правила есть ровно один раз:
   iif "lo" accept
   ct state established,related accept
   tcp dport ${ssh_port} accept
   ip protocol icmp ... accept
EOF_MANUAL
    if [[ -n "$ports_set" ]]; then
        printf '4) Добавьте единое правило AWG UDP:\n   iifname "%s" udp dport %s accept\n' "$ext_if" "$ports_set"
    else
        printf '4) AWG интерфейсов больше нет: удалите старые AWG UDP allow rules.\n'
    fi
    if [[ -n "$ifaces_set" ]]; then
        printf '5) Добавьте единый NAT masquerade:\n   iifname %s oifname "%s" masquerade\n' "$ifaces_set" "$ext_if"
    else
        printf '5) AWG интерфейсов больше нет: удалите старые AWG masquerade rules.\n'
    fi
    cat <<EOF_MANUAL

6) Для применения без наслаивания правил файл должен начинаться с:
   flush ruleset

7) Проверьте и примените:
   sudo nft -c -f ${NFTABLES_CONF}
   sudo nft -f ${NFTABLES_CONF}

Никакие изменения автоматически не были внесены.
EOF_MANUAL
}

confirm_env() {
    local var_value="$1"
    local question="$2"
    local default="$3"
    case "$var_value" in
        yes|Y|y|1|true) return 0 ;;
        no|N|n|0|false) return 1 ;;
        ask|"") confirm "$question" "$default" ;;
        *) warn "Неизвестное значение ${var_value}; спрашиваю интерактивно"; confirm "$question" "$default" ;;
    esac
}

main() {
    local ext_if ssh_port pairs ports_csv ifaces_csv remove_ports_csv remove_ifaces_csv mode candidate backup_dir backup_path had_old_bundle="no" render_error=""

    require_root
    require_cmd nft
    require_cmd systemctl

    source_env_if_exists "$MANAGER_ENV_FILE"
    source_env_if_exists "$FIREWALL_ENV_FILE"
    ext_if="$(prompt_default "Внешний интерфейс" "${EXTERNAL_IF_DEFAULT:-${EXTERNAL_IF:-$(detect_default_interface)}}")"
    [[ -n "$ext_if" ]] || die "Внешний интерфейс не может быть пустым"
    ssh_port="$(prompt_until_valid "SSH порт" "${SSH_PORT_DEFAULT:-${SSH_PORT:-22}}" validate_port)"

    pairs="$(collect_interfaces)"
    ports_csv="$(pairs_to_csv "$pairs" ports)"
    ifaces_csv="$(pairs_to_csv "$pairs" ifaces)"
    if [[ -z "$pairs" && "$(normalise_yes_no "$ALLOW_NO_INTERFACES" 2>/dev/null || printf no)" != "yes" ]]; then
        die "Не найден ни один серверный конфиг AWG в $STATE_DIR/*.conf"
    fi

    remove_ports_csv="$(csv_unique_append "${AWG_PORTS:-}" "$EXTRA_AWG_PORTS_TO_REMOVE")"
    remove_ports_csv="$(csv_unique_append "$remove_ports_csv" "$ports_csv")"
    remove_ifaces_csv="$(csv_unique_append "${AWG_IFACES:-}" "$EXTRA_AWG_IFACES_TO_REMOVE")"
    remove_ifaces_csv="$(csv_unique_append "$remove_ifaces_csv" "$ifaces_csv")"

    candidate="$(mktemp)"
    if [[ ! -e "$NFTABLES_CONF" || ! -s "$NFTABLES_CONF" ]]; then
        mode="create-template"
        generate_native_template "$ext_if" "$ssh_port" "$ports_csv" "$ifaces_csv" > "$candidate"
    elif grep -q "table ip ${NFT_TABLE_NAME}" "$NFTABLES_CONF" && ! grep -qE '^[[:space:]]*table[[:space:]]+inet[[:space:]]+filter' "$NFTABLES_CONF"; then
        mode="replace-old-managed-table"
        had_old_bundle="yes"
        generate_native_template "$ext_if" "$ssh_port" "$ports_csv" "$ifaces_csv" > "$candidate"
    elif grep -qE '^[[:space:]]*table[[:space:]]+inet[[:space:]]+filter' "$NFTABLES_CONF" && grep -qE '^[[:space:]]*table[[:space:]]+inet[[:space:]]+nat' "$NFTABLES_CONF"; then
        mode="update-existing-inet"
        grep -q "table ip ${NFT_TABLE_NAME}" "$NFTABLES_CONF" && had_old_bundle="yes"
        if ! render_native_update "$NFTABLES_CONF" "$candidate" "$ext_if" "$ssh_port" "$ports_csv" "$ifaces_csv" "$remove_ports_csv" "$remove_ifaces_csv" 2>"${candidate}.err"; then
            render_error="$(cat "${candidate}.err" 2>/dev/null || true)"
            print_manual_nft_instructions "${render_error:-не удалось распознать структуру table inet filter/nat}" "$ext_if" "$ssh_port" "$ports_csv" "$ifaces_csv"
            rm -f "$candidate" "${candidate}.err"
            exit 2
        fi
    else
        print_manual_nft_instructions "нет понятной пары table inet filter + table inet nat и это не пустой файл" "$ext_if" "$ssh_port" "$ports_csv" "$ifaces_csv"
        rm -f "$candidate"
        exit 2
    fi

    if [[ -n "$pairs" ]]; then
        printf '\nНайдены AWG интерфейсы и порты:\n%s\n' "$pairs"
    else
        printf '\nAWG интерфейсов не найдено; candidate очистит старые AWG allow/NAT rules, если они были известны из firewall.env.\n'
    fi
    printf '\nРежим nftables: %s\n' "$mode"
    printf '\nПредварительный просмотр итогового %s:\n\n' "$NFTABLES_CONF"
    cat "$candidate"
    printf '\nПроверяю синтаксис через nft -c -f ...\n'
    nft -c -f "$candidate"
    ok "Синтаксис nftables корректный"

    if confirm_env "$NFT_SAVE_CHANGES" "Сохранить этот nftables.conf с timestamp-backup старого файла?" Y; then
        backup_dir="$(create_timestamped_backup_dir nftables)"
        if [[ -e "$NFTABLES_CONF" ]]; then
            backup_path="$(backup_file_to_dir "$NFTABLES_CONF" "$backup_dir")"
            warn "Backup nftables.conf: $backup_path"
        else
            ensure_dir "$(dirname "$NFTABLES_CONF")"
        fi
        cp -- "$candidate" "$NFTABLES_CONF"
        chmod 644 "$NFTABLES_CONF"
        AWG_ACTIVE_BACKUP_DIR="$backup_dir"
        write_firewall_env "$FIREWALL_ENV_FILE" "$ext_if" "$ssh_port" "$ports_csv" "$ifaces_csv"
        AWG_ACTIVE_BACKUP_DIR=""
        ok "Файл сохранён: $NFTABLES_CONF"
        ok "firewall.env перезаписан: $FIREWALL_ENV_FILE"
        ok "Backup папка: $backup_dir"
    else
        warn "Файл не сохранён; изменения не применялись"
        rm -f "$candidate" "${candidate}.err"
        exit 0
    fi

    if confirm_env "$NFT_APPLY_NOW" "Применить сохранённые правила сейчас и включить nftables в автозагрузку?" Y; then
        if [[ "$had_old_bundle" == "yes" ]]; then
            nft delete table ip "$NFT_TABLE_NAME" 2>/dev/null || true
        fi
        nft -f "$NFTABLES_CONF"
        systemctl enable --now nftables
        ok "nftables применён через full ruleset reload"
    else
        warn "nftables не применялся автоматически. Применить вручную: sudo nft -c -f ${NFTABLES_CONF} && sudo nft -f ${NFTABLES_CONF}"
    fi

    warn "AWG services из firewall-скрипта не перезапускаются, чтобы не трогать работающие интерфейсы."
    rm -f "$candidate" "${candidate}.err"
    printf '\nСледующий шаг: scripts/04_add_client.sh <имя_клиента> [interface] или scripts/00_manage.sh\n'
}

main "$@"
